services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      # ÄNDERUNG: Speichert die Daten direkt im Host-Dateisystem im Ordner "mongo-data"
      - /data/mongo-data:/data/db
    expose:
      - "27017"
    env_file:
      - .env

  backend:
    image: ghcr.io/scalio-cloud/selfhosted-entraconsole-backend:latest
    restart: unless-stopped
    depends_on:
      - mongo
    expose:
      - "8000"
    env_file:
      - .env


  frontend:
    image: ghcr.io/scalio-cloud/selfhosted-entraconsole-frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    expose:
      - "80"
    env_file:
      - .env

  proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Volumes für die Let's Encrypt Zertifikate
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    # Prüft alle 12 Stunden, ob das Zertifikat bald abläuft und erneuert es automatisch
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"
